[package]
name = "disk_scout"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
sysinfo = "0.30"

winreg = { version = "0.10", optional = true }
winapi = { version = "0.3", features = ["winnt"], optional = true }

[features]
default = []
windows-autorun = ["winreg", "winapi"]