[package]
name = "disk_scout"
version = "0.1.0"
edition = "2024"

[dependencies]
walkdir = "2"
sysinfo = "0.37"

winreg = { version = "0.55", optional = true }
winapi = { version = "0.3", features = ["winnt"] }

